name: Pack and Publish Extension

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from manifest.json
        id: get_version
        run: |
          VERSION=$(jq -r .version public/manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Run build script
        run: |
          npm install
          npm run build

      - name: Create zip archive
        run: |
          cd build && zip -r ../botc-friends-${{ env.VERSION }}.zip ./*

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: botc-friends-${{ env.VERSION }}.zip
          path: botc-friends-${{ env.VERSION }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: botc-friends-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
